---
- name: Ensure base packages
  apt:
    name:
      - tar
      - wget
      - curl
      - unzip
      - rsync
      - openjdk-11-jre-headless
    state: present
    update_cache: true

- name: Ensure group exists
  group:
    name: "{{ hadoop_group }}"
    state: present

- name: Ensure user exists
  user:
    name: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    shell: /bin/bash
    create_home: yes
